services:
  - type: web
    name: telegram-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: BOT_TOKEN
        scope: build
      - key: CHAT_ID
        scope: build
      - key: PORT
        value: "3000"
